import type { LucideIcon } from "lucide-react";
import type { JobRoleIconKey } from "@/lib/jobRoleIconKeys";
import {
  Activity,
  AlertTriangle,
  BarChart3,
  Binary,
  BookOpenCheck,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Camera,
  CheckCircle,
  CircuitBoard,
  Cloud,
  Code2,
  Cog,
  Cpu,
  Database,
  Eye,
  FileBarChart,
  FileSearch,
  FolderKanban,
  Gauge,
  GitBranch,
  Globe,
  HardDrive,
  Headphones,
  HeartPulse,
  KeyRound,
  Laptop,
  LayoutDashboard,
  LineChart,
  MessageSquare,
  Microscope,
  MonitorPlay,
  Network,
  Phone,
  Radar,
  Radio,
  Rocket,
  Route,
  Router,
  Scale,
  ScrollText,
  Server,
  ServerCog,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Spline,
  Target,
  Terminal,
  TestTube2,
  Users,
  Wifi,
  Wrench,
} from "lucide-react";

export const JOB_ROLE_ICONS: Record<JobRoleIconKey, LucideIcon> = {
  layoutDashboard: LayoutDashboard,
  server: Server,
  testTube2: TestTube2,
  gitBranch: GitBranch,
  code2: Code2,
  smartphone: Smartphone,
  shieldCheck: ShieldCheck,
  activity: Activity,
  database: Database,
  serverCog: ServerCog,
  spline: Spline,
  bookOpenCheck: BookOpenCheck,
  folderKanban: FolderKanban,
  barChart3: BarChart3,
  scrollText: ScrollText,
  briefcase: Briefcase,
  lineChart: LineChart,
  brain: Brain,
  cpu: Cpu,
  microscope: Microscope,
  route: Route,
  messageSquare: MessageSquare,
  camera: Camera,
  users: Users,
  binary: Binary,
  terminal: Terminal,
  fileSearch: FileSearch,
  sparkles: Sparkles,
  brush: Brush,
  circuitBoard: CircuitBoard,
  monitorPlay: MonitorPlay,
  network: Network,
  router: Router,
  cloud: Cloud,
  shieldAlert: ShieldAlert,
  phone: Phone,
  wifi: Wifi,
  building2: Building2,
  headphones: Headphones,
  target: Target,
  fileBarChart: FileBarChart,
  laptop: Laptop,
  globe: Globe,
  cog: Cog,
  wrench: Wrench,
  gauge: Gauge,
  hardDrive: HardDrive,
  heartPulse: HeartPulse,
  radio: Radio,
  rocket: Rocket,
  checkCircle: CheckCircle,
  eye: Eye,
  bug: Bug,
  radar: Radar,
  alertTriangle: AlertTriangle,
  shield: Shield,
  scale: Scale,
  keyRound: KeyRound,
};
